apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app_name }}
type: Opaque
data:
#    authKey: {{ .Values.redis.authKey }}
    AUTHKEY: {{ .Values.redis.authkeyValue }}
    PASSWORD: {{ .Values.redis.password }}