apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app_name }}
type: {{ .Values.secret.type }}
data:
  username: {{ .Values.postgres.username }}
  password: {{ .Values.postgres.password }}
  database: {{ .Values.postgres.database }}