apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.labels.app2 }}
  labels:
    app: {{ .Values.app_name }}
spec:
  maxUnavailable: {{ .Values.PodDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
        app: {{ .Values.app_name }}
